[project]
name = "cryoflow"
version = "0.0.1"
description = "Plug-in-driven column-oriented data processing CLI tool with Polars LazyFrame at its core."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "polars>=1.37.1",
    "typer>=0.21.1",
]
