[project]
name = "cryoflow-sample-plugin"
version = "0.0.1"
description = "Sample plugin for cryoflow"
requires-python = ">=3.14"
dependencies = [
    "cryoflow-core",
]

[tool.uv.sources]
cryoflow-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
