[project]
name = "cryoflow-plugin-collections"
version = "0.1.0"
description = "Sample plugin for cryoflow"
requires-python = ">=3.11"
dependencies = [
    "cryoflow-core",
    "polars>=1.37.1",
    "returns>=0.23.0",
]

[tool.uv.sources]
cryoflow-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
