[project]
name = "cryoflow-plugin-collections"
version = "0.2.0"
description = "Sample plugin for cryoflow"
license = "MIT"
authors = [
    {name = "yasunori0418", email = "yasunori.kirin0418@gmail.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]
requires-python = ">=3.11"
dependencies = [
    "cryoflow-core",
    "polars>=1.37.1",
    "returns>=0.23.0",
]

[tool.uv.sources]
cryoflow-core = { workspace = true }

[project.urls]
Homepage = "https://github.com/yasunori0418/cryoflow"
Repository = "https://github.com/yasunori0418/cryoflow"
Issues = "https://github.com/yasunori0418/cryoflow/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
